### ISSUE TITLE
 Can't pickle local object 'data_provider.<locals>.<lambda>'

### ISSUE THREAD

**Issue by bigdata2013lee** [thuml/Time-Series-Library#129]
the function collate_fn in data_provider/uea.py cann't pickle while running this code in macOS. the flowing is error message:
Traceback (most recent call last):
  File "/opt/push/projects/Time-Series-Library/run.py", line 146, in <module>
    exp.train(setting)
  File "/opt/push/projects/Time-Series-Library/exp/exp_classification.py", line 102, in train
    for i, (batch_x, label, padding_mask) in enumerate(train_loader):
  File "/Users/julianlee/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 441, in __iter__
    return self._get_iterator()
  File "/Users/julianlee/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/julianlee/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1042, in __init__
    w.start()
  File "/Users/julianlee/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/julianlee/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/julianlee/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/julianlee/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/julianlee/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/julianlee/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/julianlee/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'data_provider.<locals>.<lambda>'

**Comment by wuhaixu2016** [comment]
Hi, I think this is because that you python environment. You may need to check the package versions. And our experiment are all in the linux.

**Comment by Bshara23** [comment]
Hi, I had the same problem, I'm using macos

the [lambda function at this line](https://github.com/thuml/Time-Series-Library/blob/3caf8881de7c205687c0b9517a90d7d8de0ca56e/data_provider/data_factory.py#L68) which is passed to pytorch's DataLoader causes the error, this is due to the fact that the lambda function is not picklable. Python's pickle module cannot serialize (pickle) local objects, which includes lambda functions

to fix this, replace this line
`collate_fn=lambda x: collate_fn(x, max_len=args.seq_len)`

with
`collate_fn=partial(collate_fn, max_len=args.seq_len)`

you would also need to import partial from functools
`from functools import partial`

**Comment by jurij-ch** [comment]
> to fix this, replace this line `collate_fn=lambda x: collate_fn(x, max_len=args.seq_len)`
> with `collate_fn=partial(collate_fn, max_len=args.seq_len)`
> you would also need to import partial from functools `from functools import partial`
Helped for me too. OS Windows, Python 3.8
