### ISSUE TITLE
无法获取 preds.npy 和 trues.npy 去规范化的数据。

### ISSUE THREAD

**Issue by lsl0000** [thuml/Time-Series-Library#197]
Traceback (most recent call last):
  File "run.py", line 152, in <module>
    exp.test(setting)
  File "/home/ml/lsl/Time-Series-Library-main/exp/exp_long_term_forecasting.py", line 222, in test
    outputs = test_data.inverse_transform(outputs)
  File "/home/ml/lsl/Time-Series-Library-main/data_provider/data_loader.py", line 108, in inverse_transform
    return self.scaler.inverse_transform(data)
  File "/home/ml/anaconda3/envs/pytorch1/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 1046, in inverse_transform
    X = check_array(
  File "/home/ml/anaconda3/envs/pytorch1/lib/python3.8/site-packages/sklearn/utils/validation.py", line 953, in check_array
    raise ValueError(
ValueError: Found array with dim 3. None expected <= 2.

使用--inverse后训练完后无法获取去规范化的数据，请问这是为什么？

**Comment by GuoKaku** [comment]
你好，这个bug已经修复，请验证。如果还有问题，欢迎追问。
