### ISSUE TITLE
Assistance Needed: Error in Timesnet Short term Forecasting Model Training (modelConfig)

### ISSUE THREAD

**Issue by Quantbrinx** [thuml/Time-Series-Library#323]
Hi everyone,

I've been grappling with an issue while trying to train the Timesnet short term forecasting model for the past few days and could use some guidance. I'm encountering the following error message:

Traceback (most recent call last):
  File "timesnettrainer1.py", line 439, in <module>
    train(item, "X9-gelu3-c-5dp-4096bs")
  File "timesnettrainer1.py", line 342, in train
    mc = ModelConfig()
  File "timesnettrainer1.py", line 119, in __init__
    self.x_mark
AttributeError: 'ModelConfig' object has no attribute 'x_mark'

Has anyone else come across this error, and if so, how did you resolve it? Additionally, I'm struggling to find comprehensive documentation on the parameters for ModelConfig in Timesnet for short-time forecasting. Any assistance or pointers on where to find this information would be greatly appreciated.

Thank you in advance for your help!

**Comment by wuhaixu2016** [comment]
Hi, did you use your own data? Currently, the code for short-term-exp only supports the M4 dataset. If you want to use your only dataset, you can use the long-term-exp code but change the pred_len argument to the expected value.
