### ISSUE TITLE
AttributeError: Can't pickle local object 'data_provider.<locals>.<lambda>'

### ISSUE THREAD

**Issue by hlming09** [thuml/Time-Series-Library#354]
感谢大神的代码，我在跑的时候遇到如下报错，我是在Windows系统中跑的，望赐教。

命令：
python run.py --task_name classification --is_training 1 --root_path ./dataset/Handwriting/ --model_id Handwriting --model TimesNet --data UEA --e_layers 2 --batch_size 16 --d_model 32 --d_ff 64 --top_k 3 --des 'Exp' --itr 1 --learning_rate 0.001 --train_epochs 30 --patience 10

报错：
Traceback (most recent call last):
  File "run.py", line 149, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    exp.train(setting)
  File "E:\PROJECT\Time-Series-Library\exp\exp_classification.py", line 102, in train
  File "D:\anaconda\envs\tsai\lib\multiprocessing\spawn.py", line 116, in spawn_main
    for i, (batch_x, label, padding_mask) in enumerate(train_loader):
  File "D:\anaconda\envs\tsai\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    exitcode = _main(fd, parent_sentinel)
  File "D:\anaconda\envs\tsai\lib\multiprocessing\spawn.py", line 126, in _main
    return self._get_iterator()
  File "D:\anaconda\envs\tsai\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
    return _MultiProcessingDataLoaderIter(self)
  File "D:\anaconda\envs\tsai\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "D:\anaconda\envs\tsai\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\anaconda\envs\tsai\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda\envs\tsai\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "D:\anaconda\envs\tsai\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda\envs\tsai\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'data_provider.<locals>.<lambda>'

**Comment by hlming09** [comment]
在之前closed的issue中找到了
