### ISSUE TITLE
exp_classification里，所有的flag赋值用的都是大写字母的问题

### ISSUE THREAD

**Issue by bsshor** [thuml/Time-Series-Library#363]
![image](https://github.com/thuml/Time-Series-Library/assets/53682007/f4fc4eca-6be7-421d-a33b-8501647c0384)

你好，如上图所示，在exp_classification里，所有的flag赋值用的都是大写字母。但是如下图在data_provider函数里，有一个判断标志是不是test的逻辑，用的是小写字母。我又比对了exp_anomaly_detection里关于flag的赋值，都是小写的test或train。请问为什么对exp_classification的flag赋值专门用大写呢？这个是bug吗？当我把exp_classification里，所有的flag赋值用的都更改为对应的小写字母后，再运行脚本，又会出现“Exception： No .ts files found using pattern： '*.ts”的报错
1711040776245

![image](https://github.com/thuml/Time-Series-Library/assets/53682007/56d71e84-070c-4913-8d3c-9fbeda461ff5)

添加评论

**Comment by bsshor** [comment]
这是修改exp_classification里，所有的flag为小写后的报错：
Traceback (most recent call last):
  File "/home/Time-Series-Library/run.py", line 128, in <module>
    exp = Exp(args)  # set experiments
  File "/home/Time-Series-Library/exp/exp_classification.py", line 18, in __init__
    super(Exp_Classification, self).__init__(args)
  File "/home/Time-Series-Library/exp/exp_basic.py", line 33, in __init__
    self.model = self._build_model().to(self.device)
  File "/home/Time-Series-Library/exp/exp_classification.py", line 22, in _build_model
    train_data, train_loader = self._get_data(flag='train')
  File "/home/Time-Series-Library/exp/exp_classification.py", line 35, in _get_data
    data_set, data_loader = data_provider(self.args, flag)
  File "/home/Time-Series-Library/data_provider/data_factory.py", line 57, in data_provider
    data_set = Data(
  File "/home/Time-Series-Library/data_provider/data_loader.py", line 619, in __init__
    self.all_df, self.labels_df = self.load_all(root_path, file_list=file_list, flag=flag)
  File "/home/Time-Series-Library/data_provider/data_loader.py", line 662, in load_all
    raise Exception("No .ts files found using pattern: '{}'".format(pattern))
Exception: No .ts files found using pattern: '*.ts'

**Comment by wuhaixu2016** [comment]
您好，这是因为数据集使用大写字母命名，所以其实传入的是数据集名称，不是flag
具体请见：https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L657-L658
