### ISSUE TITLE
KeyError: 'frequency_map' 

### ISSUE THREAD

**Issue by kirito5206** [thuml/Time-Series-Library#387]
使用自己的数据集进行短时序预测时出现
Traceback (most recent call last):
  File "D:/桌面/Time-Series-Library-main/run.py", line 165, in <module>
    exp.train(setting)
  File "D:\桌面\Time-Series-Library-main\exp\exp_short_term_forecasting.py", line 95, in train
    loss_value = criterion(batch_x, vars(self.args)['frequency_map'], outputs, batch_y, batch_y_mark)
KeyError: 'frequency_map'

**Comment by wuhaixu2016** [comment]
您好，如果是按照csv文件来组织数据的话，需要使用long-term-exp的相关代码，将pred_len设置为小量即可完成短期预测
