### ISSUE TITLE
Will this project become a package for time series forecasting/classification/anomaly detaction?

### ISSUE THREAD

**Issue by sysublackstar** [thuml/Time-Series-Library#41]
TimesNet, Autoformer, and other work about time series at Tsinghua are great.  Is there any chance that this project will turn into a package of time series forecasting like gluonts or pytorch-forecasting, or even more functions like classification and anomaly detaction? I think lots of developers will very wish to use it although the amount of your work may be huge😆

**Comment by wuhaixu2016** [comment]
Cool, thanks for your suggestion. We will add this into our plan.

**Comment by whatactuallyis** [comment]
Hey there, I'm interested in understanding how this library might be applied to airline ticket price prediction. The one-way price tracing appears to align closely with the benchmark dataset. However, my primary concern is its practicality when dealing with numerous provider and route combinations. Could you provide some guidance or insights on this matter? It's been a challenging concept for me to grasp.

Thank you!

**Comment by R2380324235** [comment]
When I try to run the anomaly detection scripts, some error are as follow:Traceback (most recent call last):
  File "E:\my_sql\Time-Series-Library-main\Time-Series-Library-main\run.py", line 202, in <module>
    exp.train(setting)
  File "E:\my_sql\Time-Series-Library-main\Time-Series-Library-main\exp\exp_anomaly_detection.py", line 92, in train
    outputs = self.model(batch_x, None, None, None)
  File "F:\MINICONDA\envs\times_net\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\my_sql\Time-Series-Library-main\Time-Series-Library-main\models\TimesNet.py", line 210, in forward
    dec_out = self.anomaly_detection(x_enc)
  File "E:\my_sql\Time-Series-Library-main\Time-Series-Library-main\models\TimesNet.py", line 167, in anomaly_detection
    enc_out = self.enc_embedding(x_enc, None)  # [B,T,C]
  File "F:\MINICONDA\envs\times_net\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\my_sql\Time-Series-Library-main\Time-Series-Library-main\layers\Embed.py", line 122, in forward
    x = self.value_embedding(x) + self.position_embedding(x)
  File "F:\MINICONDA\envs\times_net\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\my_sql\Time-Series-Library-main\Time-Series-Library-main\layers\Embed.py", line 41, in forward
    x = self.tokenConv(x.permute(0, 2, 1)).transpose(1, 2)
  File "F:\MINICONDA\envs\times_net\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\MINICONDA\envs\times_net\lib\site-packages\torch\nn\modules\conv.py", line 263, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "F:\MINICONDA\envs\times_net\lib\site-packages\torch\nn\modules\conv.py", line 256, in _conv_forward
    return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR. The dataset is PSM which you provide. Could you help me to solve this error?
 Thanks
