### ISSUE TITLE
单变量预测出错

### ISSUE THREAD

**Issue by mokeeqian** [thuml/Time-Series-Library#44]
作者你好，按照之前
#42 的做法，我尝试将自己的数据带入模型，进行单变量预测，出现如下错误：
```
Traceback (most recent call last):
  File "/content/drive/MyDrive/Time-Series-Library/run.py", line 145, in <module>
    exp.train(setting)
  File "/content/drive/MyDrive/Time-Series-Library/exp/exp_long_term_forecasting.py", line 135, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/Time-Series-Library/models/TimesNet.py", line 203, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
  File "/content/drive/MyDrive/Time-Series-Library/models/TimesNet.py", line 112, in forecast
    enc_out = self.enc_embedding(x_enc, x_mark_enc)  # [B,T,C]
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/Time-Series-Library/layers/Embed.py", line 124, in forward
    x = self.value_embedding(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/Time-Series-Library/layers/Embed.py", line 41, in forward
    x = self.tokenConv(x.permute(0, 2, 1)).transpose(1, 2)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/conv.py", line 255, in forward
    return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
RuntimeError: Given groups=1, weight of size [16, 7, 3], expected input[32, 1, 98] to have 7 channels, but got 1 channels instead
```
貌似是模型维度不匹配，但是我不知道该怎么修改。

以下是我的sample data：
![image](https://user-images.githubusercontent.com/45727636/225186754-0b23237b-a6ea-4354-8674-c4be5b32420a.png)

btw, 原始数据需要进行缺失值预处理吗？

**Comment by Xjt128** [comment]
你好，有点问题想请教你一下，可以回复一下吗

**Comment by ZDandsomSP** [comment]
您好，根据您的报错信息以及您提供的数据截图，您输入的序列包含的变量仅有一个（即单变量序列），而我们默认接受的变量数为7，您需要在运行run.py脚本时同时修改enc_in参数为您的变量数，另外对应输出维度的dec_in参数可能也需要根据您的需求进行修改。

关于缺失值预处理，我们目前没有这方面的工作。

**Comment by mokeeqian** [comment]
> 您好，根据您的报错信息以及您提供的数据截图，您输入的序列包含的变量仅有一个（即单变量序列），而我们默认接受的变量数为7，您需要在运行run.py脚本时同时修改enc_in参数为您的变量数，另外对应输出维度的dec_in参数可能也需要根据您的需求进行修改。
> 
> 关于缺失值预处理，我们目前没有这方面的工作。

好的，谢谢解答！
