### ISSUE TITLE
自己数据集的 TypeError: cannot unpack non-iterable NoneType object 问题

### ISSUE THREAD

**Issue by oschan77** [thuml/Time-Series-Library#481]
我尝试用 Weather 数据集的首1000行装作是自己的数据集来测试，运行的时候碰到这么一个报错。

这个跟 dataloader 有关吗？但我还是用原本的 Weather 的 dataloader 而已。请问可以怎么解决？谢谢！
```
Traceback (most recent call last):
  File "/scratch/PI/cemclo/Time-LLM/run_main.py", line 242, in <module>
    vali_loss, vali_mae_loss = vali(args, accelerator, model, vali_data, vali_loader, criterion, mae_metric)
             
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/scratch/PI/cemclo/Time-LLM/run_main.py", line 242, in <module>

0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/scratch/PI/cemclo/Time-LLM/run_main.py", line 242, in <module>
     vali_loss, vali_mae_loss = vali(args, accelerator, model, vali_data, vali_loader, criterion, mae_metric)
    vali_loss, vali_mae_loss = vali(args, accelerator, model, vali_data, vali_loader, criterion, mae_metric)
    
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:01, ?it/s]
Traceback (most recent call last):
  File "/scratch/PI/cemclo/Time-LLM/run_main.py", line 242, in <module>
  
 
             Traceback (most recent call last):
  File "/scratch/PI/cemclo/Time-LLM/run_main.py", line 242, in <module>
 Traceback (most recent call last):

0it [00:01, ?it/s]  vali_loss, vali_mae_loss = vali(args, accelerator, model, vali_data, vali_loader, criterion, mae_metric)    
 
        File "/scratch/PI/cemclo/Time-LLM/run_main.py", line 242, in <module>
   vali_loss, vali_mae_loss = vali(args, accelerator, model, vali_data, vali_loader, criterion, mae_metric)Traceback (most recent call last):
    

0it [00:01, ?it/s]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^        ^^^^ 
vali_loss, vali_mae_loss = vali(args, accelerator, model, vali_data, vali_loader, criterion, mae_metric)  File "/scratch/PI/cemclo/Time-LLM/run_main.py", line 242, in <module>
^ ^  
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  Traceback (most recent call last):
    ^^^^^^^^^^^^ ^^
                                         ^^^^^^^^^^^^^^^^^^^                               ^^^^^^^^^^^^^^^vali_loss, vali_mae_loss = vali(args, accelerator, model, vali_data, vali_loader, criterion, mae_metric)^^^^^^^^^
     ^^^^^^^^^^^^^^^^^^^^^^  File "/scratch/PI/cemclo/Time-LLM/run_main.py", line 242, in <module>

   File "/scratch/PI/cemclo/Time-LLM/utils/tools.py", line 142, in vali
 ^^  File "/scratch/PI/cemclo/Time-LLM/utils/tools.py", line 142, in vali
                        ^^^^^^ ^^     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^                        vali_loss, vali_mae_loss = vali(args, accelerator, model, vali_data, vali_loader, criterion, mae_metric)
        ^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^ for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in tqdm(enumerate(vali_loader)):for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in tqdm(enumerate(vali_loader)):^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     ^^^^^^^^^^                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/scratch/PI/cemclo/Time-LLM/utils/tools.py", line 142, in vali
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/scratch/PI/cemclo/Time-LLM/utils/tools.py", line 142, in vali
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     ^^^^^^^^
^^^^^^^^
         ^^^^^^^^for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in tqdm(enumerate(vali_loader)):  File "/scratch/PI/cemclo/Time-LLM/utils/tools.py", line 142, in vali
  File "/scratch/PI/cemclo/Time-LLM/utils/tools.py", line 142, in vali
        for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in tqdm(enumerate(vali_loader)):

^
for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in tqdm(enumerate(vali_loader)):  File "/scratch/PI/cemclo/Time-LLM/utils/tools.py", line 142, in vali
TypeError^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

           File "/scratch/PI/cemclo/Time-LLM/utils/tools.py", line 142, in vali
: ^for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in tqdm(enumerate(vali_loader)):     for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in tqdm(enumerate(vali_loader)):
cannot unpack non-iterable NoneType object

TypeError 
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^        :          ^^^^^^^^^^^^^^^^^^^
       ^for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in tqdm(enumerate(vali_loader)):TypeErrorcannot unpack non-iterable NoneType object ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^
: 
^ TypeError^cannot unpack non-iterable NoneType object^^
         ^^^^^^^^^^^^^^^^^^^^^^^^^: ^ 
^^^^^^^^^^^cannot unpack non-iterable NoneType object^ TypeError^^^^^^^^^^
^ : 
^   cannot unpack non-iterable NoneType object^     ^^^^^^
TypeError^^^^: ^^^^^^^^^^^^^^^^^^^^cannot unpack non-iterable NoneType object^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^TypeError^^^^^: ^^^^cannot unpack non-iterable NoneType object^^^^^^

TypeError: cannot unpack non-iterable NoneType object
[2024-07-31 14:57:46,358] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 25782 closing signal SIGTERM
[2024-07-31 14:57:46,523] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 25778) of binary: /home/oscarwhchan/.conda/envs/timellm/bin/python
Traceback (most recent call last):
  File "/home/oscarwhchan/.conda/envs/timellm/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/oscarwhchan/.conda/envs/timellm/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/oscarwhchan/.conda/envs/timellm/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1048, in launch_command
    multi_gpu_launcher(args)
  File "/home/oscarwhchan/.conda/envs/timellm/lib/python3.11/site-packages/accelerate/commands/launch.py", line 702, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/oscarwhchan/.conda/envs/timellm/lib/python3.11/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/oscarwhchan/.conda/envs/timellm/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscarwhchan/.conda/envs/timellm/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError
```

**Comment by wuhaixu2016** [comment]
您好，我感觉您跑的代码不是TSLib，而是Time-LLM，可以去问问官方作者。
