### ISSUE TITLE
分类任务运行报错

### ISSUE THREAD

**Issue by YWzzq** [thuml/Time-Series-Library#486]
运行了分类的Autoformer脚本报错了，好像是不能序列化什么的，求大佬看看
Traceback (most recent call last):
  File "run.py", line 202, in <module>
    exp.train(setting)
  File "D:\Time-Series-Library-main\exp\exp_classification.py", line 103, in train
    for i, (batch_x, label, padding_mask) in enumerate(train_loader):
  File "E:\anacoda\envs\Time\lib\site-packages\torch\utils\data\dataloader.py", line 440, in __iter__
    return self._get_iterator()
  File "E:\anacoda\envs\Time\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    return _MultiProcessingDataLoaderIter(self)
  File "E:\anacoda\envs\Time\lib\site-packages\torch\utils\data\dataloader.py", line 1038, in __init__
    w.start()  File "E:\anacoda\envs\Time\lib\multiprocessing\spawn.py", line 116, in spawn_main

  File "E:\anacoda\envs\Time\lib\multiprocessing\process.py", line 121, in start
    exitcode = _main(fd, parent_sentinel)
      File "E:\anacoda\envs\Time\lib\multiprocessing\spawn.py", line 126, in _main
self._popen = self._Popen(self)
  File "E:\anacoda\envs\Time\lib\multiprocessing\context.py", line 224, in _Popen
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
    return _default_context.get_context().Process._Popen(process_obj)
AttributeError: Can't pickle local object 'data_provider.<locals>.<lambda>'

**Comment by wuhaixu2016** [comment]
你好，我觉得这个问题可能是因为您的系统是windows，可以将num_workers设置为1
