### ISSUE TITLE
RuntimeError: The expanded size of the tensor (3) must match the existing size (4) at non-singleton dimension 1.  Target sizes: [5000, 3].  Tensor sizes: [5000, 4]

### ISSUE THREAD

**Issue by wtt6668888** [thuml/Time-Series-Library#549]
Traceback (most recent call last):
  File "/home/wtt/project/Time-Series-Library-main/run.py", line 166, in <module>
    exp = Exp(args)  # set experiments
  File "/home/wtt/project/Time-Series-Library-main/exp/exp_long_term_forecasting.py", line 20, in __init__
    super(Exp_Long_Term_Forecast, self).__init__(args)
  File "/home/wtt/project/Time-Series-Library-main/exp/exp_basic.py", line 44, in __init__
    self.model = self._build_model().to(self.device)
  File "/home/wtt/project/Time-Series-Library-main/exp/exp_long_term_forecasting.py", line 23, in _build_model
    model = self.model_dict[self.args.model].Model(self.args).float()
  File "/home/wtt/project/Time-Series-Library-main/models/Mamba.py", line 21, in __init__
    self.embedding = DataEmbedding(configs.enc_in, configs.d_model, configs.embed, configs.freq, configs.dropout)
  File "/home/wtt/project/Time-Series-Library-main/layers/Embed.py", line 114, in __init__
    self.position_embedding = PositionalEmbedding(d_model=d_model)
  File "/home/wtt/project/Time-Series-Library-main/layers/Embed.py", line 20, in __init__
    pe[:, 1::2] = torch.cos(position * div_term)
RuntimeError: The expanded size of the tensor (3) must match the existing size (4) at non-singleton dimension 1.  Target sizes: [5000, 3].  Tensor sizes: [5000, 4]

**Comment by wuhaixu2016** [comment]
你好，d_model应该设置为偶数，具体请见：https://github.com/thuml/Time-Series-Library/blob/main/layers/Embed.py#L19-L20
