### ISSUE TITLE
复现出现问题

### ISSUE THREAD

**Issue by DirectorZ1** [thuml/Time-Series-Library#564]
请问各位大佬，“UnicodeDecodeError: 'gbk' codec can't decode byte 0xb8 in position 4507: illegal multibyte sequence”是为什么呀 该怎么办呢

**Comment by wuhaixu2016** [comment]
您好，我觉得这个是excel格式的问题，可以尝试转存一下csv文件。

**Comment by DirectorZ1** [comment]
> 您好，我觉得这个是excel格式的问题，可以尝试转存一下csv文件。

我的文件就是csv格式的，萌新不太懂，您可以说的具体一点嘛 麻烦大佬了

**Comment by sqhsysu17** [comment]
好好检查数据。多半就是数据的问题，要么中文要么非法字符。已经给你指出位置了，看看4507行或者列。

**Comment by DirectorZ1** [comment]
> 好好检查数据。多半就是数据的问题，要么中文要么非法字符。已经给你指出位置了，看看4507行或者列。

我在复现crossformer的时候也没出现过，我的data也没有4507行
“Traceback (most recent call last):
  File "d:\code\TimeMixer-main\run.py", line 3, in <module>
    from exp.exp_long_term_forecasting import Exp_Long_Term_Forecast
  File "d:\code\TimeMixer-main\exp\exp_long_term_forecasting.py", line 3, in <module>
    from data_provider.data_factory import data_provider
  File "d:\code\TimeMixer-main\data_provider\data_factory.py", line 1, in <module>
    from data_provider.data_loader import IMF1 ,Dataset_ETT_hour, Dataset_ETT_minute, Dataset_Custom, Dataset_M4, PSMSegLoader, \
  File "d:\code\TimeMixer-main\data_provider\data_loader.py", line 7, in <module>
    from sktime.datasets import load_from_tsfile_to_dataframe
  File "D:\Conda environment\envs\mainenv\lib\site-packages\sktime\datasets\__init__.py", line 54, in <module>
    from sktime.datasets._readers_writers.arff import (
  File "D:\Conda environment\envs\mainenv\lib\site-packages\sktime\datasets\_readers_writers\arff.py", line 14, in <module>
    from sktime.transformations.base import BaseTransformer
  File "D:\Conda environment\envs\mainenv\lib\site-packages\sktime\transformations\base.py", line 56, in <module>
    from sktime.base import BaseEstimator
  File "D:\Conda environment\envs\mainenv\lib\site-packages\sktime\base\__init__.py", line 14, in <module>
    from sktime.base._base import BaseEstimator, BaseObject
  File "D:\Conda environment\envs\mainenv\lib\site-packages\sktime\base\_base.py", line 67, in <module>
    from sktime.utils._estimator_html_repr import _HTMLDocumentationLinkMixin
  File "D:\Conda environment\envs\mainenv\lib\site-packages\sktime\utils\_estimator_html_repr.py", line 190, in <module>
    _STYLE = style_file.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb8 in position 4507: illegal multibyte sequence”这是具体的信息，麻烦大佬了

**Comment by DirectorZ1** [comment]
> 我也遇到了这个问题，请问你现在解决了吗

我的数据是没问题的，和别人探讨应该是包版本的问题，但是最近比较忙自己没解决。

**Comment by cumtyhao** [comment]
解决了：把SKTIME包的版本调低一点就可以了我之前报错的是sktime 0.33.1
pip install sktime==0.24.1 -i https://pypi.tuna.tsinghua.edu.cn/simple/
