### ISSUE TITLE
TimeXer使用inverse进行反归一化报错

### ISSUE THREAD

**Issue by AMINUSFELIX** [thuml/Time-Series-Library#600]
>>>>>>>testing : long_term_forecast_NP_168_24_TimeXer_custom_ftMS_sl168_ll48_pl24_dm512_nh8_el3_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_Timexer-MS_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 10460
Traceback (most recent call last):
  File "run.py", line 196, in <module>
    exp.test(setting)
  File "G:\PythonProjects\Time-Series-Library-main2\exp\exp_long_term_forecasting.py", line 205, in test
    outputs = test_data.inverse_transform(outputs.reshape(shape[0] * shape[1], -1)).reshape(shape)
  File "G:\PythonProjects\Time-Series-Library-main2\data_provider\data_loader.py", line 435, in inverse_transform
    return self.scaler.inverse_transform(data)
  File "G:\anaconda3\envs\TimeXer\lib\site-packages\sklearn\preprocessing\_data.py", line 1052, in inverse_transform
    X *= self.scale_
ValueError: non-broadcastable output operand with shape (96,1) doesn't match the broadcast shape (96,3)

**Comment by wang-lucy** [comment]
相关问题已在TimeXer仓库中回答，请见：https://github.com/thuml/TimeXer/issues/12
