### ISSUE TITLE
为什么短期预测的代码跑不了，会报错

### ISSUE THREAD

**Issue by zhurong-dot** [thuml/Time-Series-Library#623]
Traceback (most recent call last):
  File "run.py", line 191, in <module>
    exp.train(setting)
  File "C:\Users\ZRCC\Desktop\wenxian\123\Time-Series-Library-main\exp\exp_short_term_forecasting.py", line 54, in train
    train_data, train_loader = self._get_data(flag='train')
  File "C:\Users\ZRCC\Desktop\wenxian\123\Time-Series-Library-main\exp\exp_short_term_forecasting.py", line 36, in _get_data
    data_set, data_loader = data_provider(self.args, flag)
  File "C:\Users\ZRCC\Desktop\wenxian\123\Time-Series-Library-main\data_provider\data_factory.py", line 67, in data_provider
    data_set = Data(
  File "C:\Users\ZRCC\Desktop\wenxian\123\Time-Series-Library-main\data_provider\data_loader.py", line 333, in __init__
    self.__read_data__()
  File "C:\Users\ZRCC\Desktop\wenxian\123\Time-Series-Library-main\data_provider\data_loader.py", line 341, in __read_data__
    training_values = np.array(
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (414,) + inhomogeneous part.

**Comment by Musongwhk** [comment]
你能够提供你使用的数据集和详细脚本吗？这样方便我们解决bug。对于m4数据集，我们这里都是能够跑通的

**Comment by zhurong-dot** [comment]
我觉得这应该是data path的问题，在M4脚本中没有指定data path,这data [path按照默认的etth1数据集。但m4数据集中有很多数据集（训练和测试集）我不知道换哪个
![25c02abc35f680131b4bd8a0163e738](https://github.com/user-attachments/assets/36bfc67d-1a1d-4445-bbe3-ee9c9c95fdc1)

**Comment by Musongwhk** [comment]
（1）在处理m4数据集时会忽略data_path参数，而是根据root_path和seasonal_patterns这两个参数确定数据。

**Comment by Musongwhk** [comment]
（1）在处理m4数据集时会忽略data_path参数，而是根据root_path和seasonal_patterns这两个参数确定数据。
（2）m4数据集由年度、季度、月度、每周、每日和每小时为间隔的数据的时间序列组成，并分为训练和测试集
（3）如果你希望使用自己的数据集，那么需要参考data_loader.py中的代码来处理自己的数据集

**Comment by zhurong-dot** [comment]
那是不是在Windows中的问题呀，我在windows中输入命令还是一样的错
![Uploading 131eb55da33ad352de8d5747ef5c3ca.png…]()

**Comment by wuhaixu2016** [comment]
感谢 @Musongwhk 的回复，可以修改numpy版本解决

**Comment by a1473838623** [comment]
py3.12无法安装numpy 1.23.5版本，可能可以通过修改以下代码解决：
```python
training_values = np.array(
    [v[~np.isnan(v)] for v in dataset.values[dataset.groups == self.seasonal_patterns]],
    dtype=object
) 
```
