### ISSUE TITLE
我想要修改预测的参数例如'--seq_len', '20',     '--pred_len', '5',，代码会报错，我需要去修改那些东西呢

### ISSUE THREAD

**Issue by zhurong-dot** [thuml/Time-Series-Library#627]

**Comment by wuhaixu2016** [comment]
您好，这个issue不是很细节，具体是哪些哪个脚本（什么数据集、什么模型）呢？

我觉得这样报错的需要看看模型是否有一些特别的长度要求。

**Comment by zhurong-dot** [comment]
我这样给你描述这个问题，我主要改了 "--features", "MS"后,我想要反归一化后的PDF，报错我怎么改 "我的命令--data_path", "ETTh1.csv",
    "--model_id", "ETTh1_96_96",
    "--model", model_name,
    "--data", "ETTh1",
    "--features", "MS",
    "--seq_len", "96",
    "--label_len", "48",
    "--pred_len", "96",
    "--e_layers", "2",
    "--d_layers", "1",
    "--factor", "3",
    "--enc_in", "7",
    "--dec_in", "7",
    "--c_out", "7",
    "--des", "Exp",
    "--itr", "1"
model_name = "iTransformer"我该怎么解决

Traceback (most recent call last):
  File "run.py", line 194, in <module>
    exp.test(setting)
  File "G:\Time-Series-Library-main\Time-Series-Library-main\exp\exp_long_term_forecasting.py", line 207, in test
    outputs = test_data.inverse_transform(outputs.reshape(shape[0] * shape[1], -1)).reshape(shape)
  File "G:\Time-Series-Library-main\Time-Series-Library-main\data_provider\data_loader.py", line 109, in inverse_transform
    return self.scaler.inverse_transform(data)
  File "F:\shuoAPP\anaconda\envs\QHZS\lib\site-packages\sklearn\preprocessing\_data.py", line 1052, in inverse_transform
    X *= self.scale_
ValueError: operands could not be broadcast together with shapes (3072,49) (7,) (3072,49)
